modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="woodster"
version="2.2.3"
displayName="Woodster"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
credits="Jusey1, Burack"
authors="Jusey1"
description="Books & Ladders"

[[dependencies.woodster]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5]"
    ordering="NONE"
    side="BOTH"
